"""Updated locations table

Revision ID: 08a512454738
Revises: cfce7a4a30cf
Create Date: 2026-07-27 20:02:32.006396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08a512454738'
down_revision: Union[str, Sequence[str], None] = 'cfce7a4a30cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lat_lon', 'locations', ['latitude', 'longitude'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_lat_lon', 'locations', type_='unique')
    # ### end Alembic commands ###
