"""Edit group_locations table

Revision ID: 278a960ef7b7
Revises: a995e75704c5
Create Date: 2026-08-03 19:40:14.944400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278a960ef7b7'
down_revision: Union[str, Sequence[str], None] = 'a995e75704c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_locations', sa.Column('display_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'group_locations', ['group_id', 'display_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_locations', type_='unique')
    op.drop_column('group_locations', 'display_name')
    # ### end Alembic commands ###
