"""Edit user_locations table

Revision ID: 2a93fde1edeb
Revises: 9267da1332fc
Create Date: 2026-08-31 19:39:57.054217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a93fde1edeb'
down_revision: Union[str, Sequence[str], None] = '9267da1332fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_locations_name_key'), 'user_locations', type_='unique')
    op.drop_column('user_locations', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('user_locations_name_key'), 'user_locations', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
