"""Updated user_groups

Revision ID: 33cbb8d3a221
Revises: 340e6c1d5000
Create Date: 2026-07-29 15:52:51.307550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33cbb8d3a221'
down_revision: Union[str, Sequence[str], None] = '340e6c1d5000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_groups_id_fkey'), 'user_groups', type_='foreignkey')
    op.create_foreign_key(None, 'user_groups', 'users', ['user_id'], ['id'])
    op.drop_column('user_groups', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.create_foreign_key(op.f('user_groups_id_fkey'), 'user_groups', 'users', ['id'], ['id'])
    op.drop_column('user_groups', 'user_id')
    # ### end Alembic commands ###
