"""Remove uniqueness in group_locations

Revision ID: 42c5aeb1a2e7
Revises: 278a960ef7b7
Create Date: 2026-08-04 12:11:54.876595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42c5aeb1a2e7'
down_revision: Union[str, Sequence[str], None] = '278a960ef7b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('group_locations_group_id_display_name_key'), 'group_locations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('group_locations_group_id_display_name_key'), 'group_locations', ['group_id', 'display_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
