"""Remove origin_id as primary key from invite table

Revision ID: 515c706dbfcf
Revises: 7613d431f3a7
Create Date: 2026-07-31 18:26:31.688907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515c706dbfcf'
down_revision: Union[str, Sequence[str], None] = '7613d431f3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
