"""Edit user_locations table

Revision ID: 5463fbbc31db
Revises: 08a512454738
Create Date: 2026-07-27 20:39:40.213946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5463fbbc31db'
down_revision: Union[str, Sequence[str], None] = '08a512454738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_locations', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_locations', type_='foreignkey')
    op.drop_column('user_locations', 'user_id')
    # ### end Alembic commands ###
