"""Add ondelete constraints to foreign keys

Revision ID: 62dfa6a19d17
Revises: 42c5aeb1a2e7
Create Date: 2026-08-07 14:35:03.302874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62dfa6a19d17'
down_revision: Union[str, Sequence[str], None] = '42c5aeb1a2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('group_locations_location_id_fkey'), 'group_locations', type_='foreignkey')
    op.drop_constraint(op.f('group_locations_group_id_fkey'), 'group_locations', type_='foreignkey')
    op.create_foreign_key(None, 'group_locations', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_locations', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('invites_group_id_fkey'), 'invites', type_='foreignkey')
    op.drop_constraint(op.f('invites_user_id_fkey'), 'invites', type_='foreignkey')
    op.drop_constraint(op.f('invites_origin_id_fkey'), 'invites', type_='foreignkey')
    op.create_foreign_key(None, 'invites', 'users', ['origin_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invites', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'invites', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_groups_location_id_fkey'), 'user_groups', type_='foreignkey')
    op.drop_constraint(op.f('user_groups_user_id_fkey'), 'user_groups', type_='foreignkey')
    op.drop_constraint(op.f('user_groups_group_id_fkey'), 'user_groups', type_='foreignkey')
    op.create_foreign_key(None, 'user_groups', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_groups', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('user_locations_location_id_fkey'), 'user_locations', type_='foreignkey')
    op.drop_constraint(op.f('user_locations_user_id_fkey'), 'user_locations', type_='foreignkey')
    op.create_foreign_key(None, 'user_locations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_locations', 'locations', ['location_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_default_location_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'locations', ['default_location_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_default_location_id_fkey'), 'users', 'locations', ['default_location_id'], ['id'])
    op.drop_constraint(None, 'user_locations', type_='foreignkey')
    op.drop_constraint(None, 'user_locations', type_='foreignkey')
    op.create_foreign_key(op.f('user_locations_user_id_fkey'), 'user_locations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_locations_location_id_fkey'), 'user_locations', 'locations', ['location_id'], ['id'])
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.create_foreign_key(op.f('user_groups_group_id_fkey'), 'user_groups', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(op.f('user_groups_user_id_fkey'), 'user_groups', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('user_groups_location_id_fkey'), 'user_groups', 'locations', ['location_id'], ['id'])
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.create_foreign_key(op.f('invites_origin_id_fkey'), 'invites', 'users', ['origin_id'], ['id'])
    op.create_foreign_key(op.f('invites_user_id_fkey'), 'invites', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('invites_group_id_fkey'), 'invites', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'group_locations', type_='foreignkey')
    op.drop_constraint(None, 'group_locations', type_='foreignkey')
    op.create_foreign_key(op.f('group_locations_group_id_fkey'), 'group_locations', 'groups', ['group_id'], ['id'])
    op.create_foreign_key(op.f('group_locations_location_id_fkey'), 'group_locations', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###
