"""Edit invites table

Revision ID: 7613d431f3a7
Revises: 7e817a4980ea
Create Date: 2026-07-31 07:34:21.858760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7613d431f3a7'
down_revision: Union[str, Sequence[str], None] = '7e817a4980ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invites', sa.Column('origin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'invites', 'users', ['origin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invites', type_='foreignkey')
    op.drop_column('invites', 'origin_id')
    # ### end Alembic commands ###
