"""Edit user_groups table

Revision ID: a995e75704c5
Revises: b61b4b1f0169
Create Date: 2026-08-03 16:28:55.673360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a995e75704c5'
down_revision: Union[str, Sequence[str], None] = 'b61b4b1f0169'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'user_groups', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_groups', type_='foreignkey')
    op.drop_column('user_groups', 'location_id')
    # ### end Alembic commands ###
