"""Add default_location_id to users table

Revision ID: b11ed61e3306
Revises: 5463fbbc31db
Create Date: 2026-07-28 11:51:42.433561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11ed61e3306'
down_revision: Union[str, Sequence[str], None] = '5463fbbc31db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'locations', ['default_location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'default_location_id')
    # ### end Alembic commands ###
