"""Edit user_locations table

Revision ID: b61b4b1f0169
Revises: d0a4f4cbc050
Create Date: 2026-08-03 16:08:57.197407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b61b4b1f0169'
down_revision: Union[str, Sequence[str], None] = 'd0a4f4cbc050'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_locations', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user_locations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_locations', type_='unique')
    op.drop_column('user_locations', 'name')
    # ### end Alembic commands ###
