"""Updated user_groups table

Revision ID: d0a4f4cbc050
Revises: 515c706dbfcf
Create Date: 2026-08-02 15:42:49.879444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0a4f4cbc050'
down_revision: Union[str, Sequence[str], None] = '515c706dbfcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_groups', sa.Column('car_capacity', sa.Integer(), nullable=False))
    op.add_column('user_groups', sa.Column('is_passenger', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_groups', 'is_passenger')
    op.drop_column('user_groups', 'car_capacity')
    # ### end Alembic commands ###
